/* ═══════════════════════════════════════════════════════════════════════════
   LEÇONS ÉDUCATIVES — 41 cours couvrant le programme brevet (collège/lycée)
   Chaque entrée : motsCles (mots-clés déclencheurs) + reponse (fonction → string)
   ═══════════════════════════════════════════════════════════════════════════ */

const LESSONS = [

  /* ════════════════════════════════════════
     📐 MATHÉMATIQUES
     ════════════════════════════════════════ */

  { motsCles: ["pythagore","hypoténuse","triangle rectangle"],
    reponse: () => `📚 **Théorème de Pythagore**\n\n🔑 **Principe**\nDans un **triangle rectangle** : **c² = a² + b²**\nc = hypoténuse (côté face à l'angle droit, le plus long)\n\n📖 **Explication**\nSi tu connais 2 côtés, tu trouves le 3ème :\n• Chercher l'hypoténuse c : c = √(a² + b²)\n• Chercher un petit côté a : a = √(c² − b²)\n\n✏️ **Exemple résolu**\na = 3 cm, b = 4 cm → c² = 9 + 16 = 25 → c = **5 cm**\n\n💡 **À retenir**\n• Fonctionne UNIQUEMENT dans un triangle rectangle\n• Triples pythagoriciens classiques : (3,4,5) · (5,12,13) · (8,15,17)\n• Réciproque : si c² = a²+b² alors le triangle EST rectangle\n\n🎯 **Question** : Triangle de côtés 6, 8 et 10 cm. Est-il rectangle ?` },

  { motsCles: ["thalès","proportionnalite cotes","droites paralleles"],
    reponse: () => `📚 **Théorème de Thalès**\n\n🔑 **Principe**\nSi (DE) ∥ (BC) dans un triangle, alors :\n**AD/AB = AE/AC = DE/BC**\n\n📖 **Méthode**\n1. Vérifier que les droites sont parallèles\n2. Poser l'égalité des rapports\n3. Faire un produit en croix\n\n✏️ **Exemple résolu**\nAD = 3, AB = 9, DE = 4. Calculer BC.\n→ 3/9 = 4/BC → BC = (4×9)/3 = **12**\n\n💡 **À retenir**\n• Condition OBLIGATOIRE : droites parallèles\n• Thalès réciproque : égalité des rapports → droites parallèles\n• Toujours écrire les rapports dans le même ordre !\n\n🎯 **Question** : AD = 5, AB = 15, AE = 4. Calcule AC.` },

  { motsCles: ["fraction","fractions","numérateur","dénominateur","simplifier fraction"],
    reponse: () => `📚 **Les fractions**\n\n🔑 **Définition**\nUne fraction = **numérateur / dénominateur** (le dénominateur ≠ 0)\nEx : 3/4 = 3 parties sur 4\n\n📖 **Opérations**\n**Addition/Soustraction** → même dénominateur obligatoire :\n1/3 + 1/4 = 4/12 + 3/12 = **7/12**\n\n**Multiplication** → numérateur × numérateur :\n2/3 × 3/5 = 6/15 = **2/5**\n\n**Division** → multiplier par l'inverse :\n2/3 ÷ 4/5 = 2/3 × 5/4 = 10/12 = **5/6**\n\n**Simplifier** → diviser num. ET dénom. par le même nombre :\n12/18 ÷ 6 = **2/3**\n\n💡 **À retenir**\n• Pour additionner : trouver le dénominateur commun (PPCM)\n• Une fraction est irréductible quand num. et dénom. n'ont plus de diviseur commun\n\n🎯 **Question** : Calcule 2/5 + 3/4 et donne le résultat simplifié.` },

  { motsCles: ["puissance","puissances","racine carree","exposant","notation scientifique"],
    reponse: () => `📚 **Puissances et racines carrées**\n\n🔑 **Définitions**\n• **aⁿ** = a multiplié n fois par lui-même : 2⁴ = 2×2×2×2 = **16**\n• **a⁰ = 1** pour tout a ≠ 0\n• **a⁻ⁿ = 1/aⁿ** : 10⁻² = 1/100 = **0,01**\n• **√a** = nombre positif dont le carré = a : √25 = **5**\n\n📖 **Règles de calcul**\naⁿ × aᵐ = aⁿ⁺ᵐ (même base → additionne les exposants)\naⁿ ÷ aᵐ = aⁿ⁻ᵐ\n(aⁿ)ᵐ = aⁿˣᵐ\n\n📖 **Notation scientifique**\na × 10ⁿ avec 1 ≤ a < 10 : 3 400 = **3,4 × 10³**\n\n💡 **Carrés à connaître par cœur**\n1 4 9 16 25 36 49 64 81 100 121 144\n\n🎯 **Question** : Simplifie 3⁵ × 3⁻² et calcule √144.` },

  { motsCles: ["proportionnalite","pourcentage","regle de trois","taux","coefficient multiplicateur"],
    reponse: () => `📚 **Proportionnalité et pourcentages**\n\n🔑 **Tableau de proportionnalité**\nDeux grandeurs sont proportionnelles si leurs quotients sont constants.\n| Quantité | 2 | 5 | 8 |\n| Prix     | 6 | 15| 24|\nCoefficient = 3 (on multiplie par 3)\n\n📖 **Règle de trois**\n2 kg coûte 6€. Combien pour 5 kg ?\n→ 5 × 6 / 2 = **15 €**\n\n📖 **Pourcentages**\n• p% de a = a × p/100\n• 20% de 150 = 150 × 20/100 = **30**\n• Augmentation de t% : multiplier par (1 + t/100)\n• Réduction de t% : multiplier par (1 − t/100)\n• Ex : −15% sur 80€ = 80 × 0,85 = **68 €**\n\n💡 **À retenir**\n• Coefficient multiplicateur = 1 ± taux/100\n• Pour trouver le taux d'évolution : (val.finale − val.initiale)/val.initiale × 100\n\n🎯 **Question** : Un article coûte 120 €. Après 25% de réduction, quel est son prix ?` },

  { motsCles: ["equation","équation","inéquation","résoudre","premier degré"],
    reponse: () => `📚 **Équations du 1er degré**\n\n🔑 **Définition**\nUne équation est une égalité avec une inconnue x à trouver.\nPrincipe : faire les mêmes opérations des DEUX côtés.\n\n📖 **Méthode**\n1. Développer et réduire\n2. Regrouper les termes en x d'un côté, les nombres de l'autre\n3. Diviser par le coefficient de x\n\n✏️ **Exemple résolu**\n3x + 7 = 2x − 5\n→ 3x − 2x = −5 − 7\n→ x = **−12**\n\n📖 **Inéquations**\nMême méthode MAIS : si on multiplie/divise par un **nombre négatif**, le sens de l'inégalité s'inverse !\n−2x > 6 → x < **−3** (signe inversé car ÷ par −2)\n\n💡 **À retenir**\n• Vérifier toujours ta solution en la remplaçant dans l'équation de départ\n• Équation du 2nd degré : ax² + bx + c = 0 → discriminant Δ = b² − 4ac\n\n🎯 **Question** : Résous 5x − 3 = 2x + 9` },

  { motsCles: ["fonction","f(x)","tableau de valeurs","représentation graphique","image","antécédent"],
    reponse: () => `📚 **Les fonctions**\n\n🔑 **Définition**\nUne fonction f associe à chaque valeur x une image f(x).\nf(x) = 2x + 3 : pour x = 4 → f(4) = 2×4+3 = **11**\n\n📖 **Vocabulaire**\n• **Image** de x = f(x) (résultat)\n• **Antécédent** de y = la valeur x telle que f(x) = y\n• **Domaine de définition** = ensemble des x autorisés\n\n📖 **Fonctions linéaires et affines**\n• Linéaire : **f(x) = ax** → droite passant par l'origine\n• Affine : **f(x) = ax + b** → droite quelconque\n  a = pente (coefficient directeur), b = ordonnée à l'origine\n\n📖 **Tableau de valeurs**\nx : −2, −1, 0, 1, 2\nf(x) = 3x−1 : −7, −4, −1, 2, 5\n\n💡 **À retenir**\n• Sur un graphique : image = ordonnée · antécédent = abscisse\n• Pente positive → fonction croissante ; pente négative → décroissante\n\n🎯 **Question** : f(x) = −2x + 5. Calcule f(3) et trouve l'antécédent de 1.` },

  { motsCles: ["trigonométrie","sinus","cosinus","tangente","sin","cos","tan","angle"],
    reponse: () => `📚 **Trigonométrie (triangle rectangle)**\n\n🔑 **Les 3 formules (SOH-CAH-TOA)**\nDans un triangle rectangle d'angle aigu α :\n\n• **sin(α) = côté opposé / hypoténuse**\n• **cos(α) = côté adjacent / hypoténuse**\n• **tan(α) = côté opposé / côté adjacent**\n\n📖 **Moyen mémo** : SOHCAHTOA\nSin=Opp/Hyp · Cos=Adj/Hyp · Tan=Opp/Adj\n\n✏️ **Exemple résolu**\nTriangle rectangle, angle α = 30°, hypoténuse = 10 cm.\n→ Côté opposé = 10 × sin(30°) = 10 × 0,5 = **5 cm**\n\n💡 **Valeurs à connaître**\n| Angle | 0° | 30° | 45° | 60° | 90° |\n| sin   | 0  | 0,5 | √2/2| √3/2| 1   |\n| cos   | 1  |√3/2 | √2/2| 0,5 | 0   |\n\n🎯 **Question** : Dans un triangle rectangle, angle = 45°, côté adjacent = 8 cm. Calcule l'hypoténuse.` },

  { motsCles: ["aire","périmètre","surface","carré","rectangle","cercle","triangle","losange","trapèze"],
    reponse: () => `📚 **Aires et périmètres**\n\n📐 **PÉRIMÈTRES**\n• Carré : P = 4a\n• Rectangle : P = 2(L + l)\n• Cercle : P = 2πr (r = rayon)\n• Triangle : P = a + b + c\n\n📐 **AIRES**\n• Carré : A = a²\n• Rectangle : A = L × l\n• Triangle : A = base × hauteur / 2\n• Cercle : A = πr² (π ≈ 3,14)\n• Trapèze : A = (B + b) × h / 2 (B et b = bases parallèles)\n• Losange : A = d × D / 2 (d et D = diagonales)\n\n✏️ **Exemple**\nCercle de rayon 5 cm :\n→ Périmètre = 2 × π × 5 ≈ **31,4 cm**\n→ Aire = π × 5² ≈ **78,5 cm²**\n\n💡 **À retenir**\n• Aire s'exprime en cm², m², km²\n• Périmètre s'exprime en cm, m, km\n\n🎯 **Question** : Calcule l'aire et le périmètre d'un rectangle 6 cm × 9 cm.` },

  { motsCles: ["volume","cube","pavé","cylindre","cône","sphère","pyramide","solide"],
    reponse: () => `📚 **Les volumes**\n\n📦 **FORMULES**\n• **Cube** de côté a : V = a³\n• **Pavé droit** : V = L × l × h\n• **Cylindre** : V = π × r² × h\n• **Cône** : V = (1/3) × π × r² × h\n• **Sphère** : V = (4/3) × π × r³\n• **Pyramide** : V = (1/3) × Aire_base × h\n\n✏️ **Exemple**\nCylindre : r = 3 cm, h = 10 cm\n→ V = π × 9 × 10 = **90π ≈ 282,7 cm³**\n\n💡 **À retenir**\n• Volume s'exprime en cm³, m³, L (1 L = 1 dm³ = 1 000 cm³)\n• Développé d'un cylindre : rectangle + 2 disques\n\n🎯 **Question** : Calcule le volume d'un cube de côté 4 cm.` },

  { motsCles: ["probabilite","probabilités","chance","aléatoire","événement","fréquence"],
    reponse: () => `📚 **Les probabilités**\n\n🔑 **Formule de base**\n**P(A) = nombre de cas favorables / nombre de cas possibles**\n• P = 0 → événement impossible\n• P = 0,5 → une chance sur deux\n• P = 1 → événement certain\n\n✏️ **Exemple résolu**\nDé à 6 faces. P(obtenir un nombre pair) ?\n→ Favorables : {2, 4, 6} = 3 cas\n→ Possibles : {1,2,3,4,5,6} = 6 cas\n→ P = 3/6 = **1/2 = 0,5**\n\n💡 **Propriétés importantes**\n• Somme de toutes les probabilités = **1**\n• P(contraire de A) = 1 − P(A)\n• Si équiprobable : toutes les issues ont la même proba\n• Expérience à 2 étapes : tableau à double entrée ou arbre\n\n🎯 **Question** : Sac : 3 billes rouges, 5 bleues, 2 vertes. Quelle est P(bleue) et P(pas rouge) ?` },

  { motsCles: ["statistique","statistiques","moyenne","médiane","étendue","effectif","quartile"],
    reponse: () => `📚 **Les statistiques**\n\n🔑 **Indicateurs de position**\n• **Moyenne** = somme des valeurs ÷ nombre de valeurs\n• **Médiane** = valeur du milieu (série rangée dans l'ordre)\n  Si n pair : médiane = moyenne des 2 valeurs centrales\n• **Mode** = valeur la plus fréquente\n\n🔑 **Indicateurs de dispersion**\n• **Étendue** = valeur max − valeur min\n• **Q1** (1er quartile) = médiane de la 1ère moitié\n• **Q3** (3ème quartile) = médiane de la 2ème moitié\n\n✏️ **Exemple résolu** : 8, 9, 10, 12, 12, 14, 16\n→ **Moyenne** = (8+9+10+12+12+14+16)/7 = 81/7 ≈ **11,6**\n→ **Médiane** = **12** (4ème valeur sur 7)\n→ **Étendue** = 16−8 = **8**\n\n💡 **Lecture de diagrammes**\n• Barres : effectifs · Circulaire : fréquences · Histogramme : données regroupées\n\n🎯 **Question** : Calcule la moyenne et la médiane de : 5, 7, 3, 8, 7, 10, 4` },

  /* ════════════════════════════════════════
     📝 FRANÇAIS
     ════════════════════════════════════════ */

  { motsCles: ["figure de style","métaphore","comparaison","personnification","hyperbole","anaphore","allitération","antithèse","oxymore","euphémisme"],
    reponse: () => `📚 **Les figures de style**\n\n🔑 **Figures d'analogie**\n• **Comparaison** : outil (comme/tel/pareil à) → *"courageux comme un lion"*\n• **Métaphore** : sans outil → *"c'est un lion sur le terrain"*\n• **Personnification** : objet/animal avec traits humains → *"le vent gémissait"*\n• **Allégorie** : idée abstraite représentée par image concrète\n\n🔑 **Figures d'amplification**\n• **Hyperbole** : exagération → *"je t'ai attendu des siècles"*\n• **Accumulation** : liste d'éléments → *"il court, il vole, il tombe"*\n• **Gradation** : intensité croissante\n\n🔑 **Figures de répétition**\n• **Anaphore** : même mot en début de vers/phrase\n• **Allitération** : répétition d'une consonne → *"souffles si froids"*\n• **Assonance** : répétition d'une voyelle\n\n🔑 **Figures d'opposition**\n• **Antithèse** : deux idées opposées → *"ange aux airs de démon"*\n• **Oxymore** : contradiction dans une même expression → *"obscure clarté"*\n\n💡 **Au brevet : NOMMER + CITER le passage + EXPLIQUER l'effet**\n\n🎯 **Question** : "Les étoiles dansaient dans le ciel." Identifie la figure et explique son effet.` },

  { motsCles: ["conjugaison","subjonctif","conditionnel","imparfait","passé composé","futur","plus-que-parfait","passé simple","mode verbal"],
    reponse: () => `📚 **Conjugaison — Les temps du brevet**\n\n🕐 **TEMPS DE L'INDICATIF**\n• **Présent** : action actuelle → *je mange*\n• **Imparfait** : passé duratif/répétitif → *je mangeais* (−ais/−ait/−ions/−iez/−aient)\n• **Passé composé** : passé accompli → *j'ai mangé / je suis parti(e)*\n• **Passé simple** : littéraire, action ponctuelle → *il mangea / il vint*\n• **Plus-que-parfait** : avant un autre passé → *j'avais mangé*\n• **Futur simple** : avenir → *je mangerai* (inf. + −ai/−as/−a/−ons/−ez/−ont)\n• **Futur antérieur** : avant un autre futur → *j'aurai mangé*\n\n🕐 **AUTRES MODES**\n• **Conditionnel présent** : hypothèse → *je mangerais* (radical futur + terminaisons imparfait)\n• **Subjonctif présent** : doute/souhait après "que" → *qu'il mange*\n• **Impératif** : ordre → *mange ! mangeons !*\n\n💡 **Pièges**\n• Passé composé avec ÊTRE → accord du participe passé\n• "Quand" = futur (jamais conditionnel) : *Quand il viendra...*\n• Verbes irréguliers : être, avoir, aller, faire, venir, pouvoir, vouloir\n\n🎯 **Question** : Conjugue "venir" au passé composé et au subjonctif présent (toutes personnes).` },

  { motsCles: ["nature des mots","classe grammaticale","nom","adjectif","adverbe","pronom","déterminant","conjonction","préposition"],
    reponse: () => `📚 **La nature des mots (classes grammaticales)**\n\n📖 **Mots VARIABLES** (qui changent selon genre/nombre)\n• **Nom** : désigne un être ou une chose → *chien, maison, amour*\n• **Déterminant** : accompagne le nom → *le, un, ce, mon, trois*\n• **Adjectif qualificatif** : qualifie le nom → *grand, beau, intelligent*\n• **Pronom** : remplace un nom → *il, le, lui, ce, qui, dont*\n• **Verbe** : exprime une action/état → *courir, être, sembler*\n\n📖 **Mots INVARIABLES**\n• **Adverbe** : modifie verbe/adj → *vite, très, souvent, hier*\n• **Préposition** : relie des mots → *à, de, dans, pour, avec, sur*\n• **Conjonction de coordination** : mais, ou, et, donc, or, ni, car\n• **Conjonction de subordination** : que, parce que, quand, si...\n\n💡 **Astuce** : Pour trouver la nature, demande-toi CE QU'EST le mot (pas ce qu'il fait)\n\n🎯 **Question** : Donne la nature de chaque mot : *Les petits enfants courent très vite dans le jardin.*` },

  { motsCles: ["fonction grammaticale","sujet","cod","coi","attribut","complément circonstanciel","épithète","apposition"],
    reponse: () => `📚 **Les fonctions grammaticales**\n\n📖 **Fonctions du NOM/GROUPE NOMINAL**\n• **Sujet** : fait l'action → *Le chien court.* (Qui est-ce qui court ?)\n• **COD** (complément d'objet direct) : complète sans préposition → *Je lis **un livre**.* (Quoi ?)\n• **COI** (complément d'objet indirect) : complète avec préposition (à, de) → *Je pense **à toi**.* (À qui ?)\n• **Attribut du sujet** : après être/paraître/sembler → *Il est **gentil**.*\n• **Complément circonstanciel** : indique où, quand, comment, pourquoi → *Il court **dans le parc**.*\n\n📖 **Fonctions de l'ADJECTIF**\n• **Épithète** : directement lié au nom → *un **grand** homme*\n• **Attribut** : lié au nom via un verbe → *Cet homme est **grand**.*\n\n💡 **Méthode pour trouver la fonction**\n1. Trouver le verbe\n2. Poser les questions : Qui ? Quoi ? À qui ? À quoi ? Où ? Quand ? Comment ?\n\n🎯 **Question** : Analyse les fonctions dans : *Maria offre un cadeau à son ami chaque année.*` },

  { motsCles: ["type de texte","texte narratif","texte descriptif","texte argumentatif","texte explicatif","texte injonctif"],
    reponse: () => `📚 **Les types de textes**\n\n📖 **5 types principaux**\n\n**Narratif** → raconte une histoire (passé simple, imparfait, connecteurs temporels)\n→ *"Un soir, il entra dans la maison..."*\n\n**Descriptif** → décrit un lieu/personnage (adjectifs, verbes d'état, présent)\n→ *"La pièce était sombre, froide et silencieuse..."*\n\n**Argumentatif** → défend une opinion (connecteurs logiques : donc, or, ainsi)\n→ *"Je pense que... car... de plus... en conclusion..."*\n\n**Explicatif** → informe, explique (présent, vocabulaire précis, connecteurs)\n→ *"La photosynthèse est un processus par lequel..."*\n\n**Injonctif** → donne des ordres/conseils (impératif, infinitif, futur)\n→ *"Mélangez les ingrédients. Faites cuire 30 min."*\n\n💡 **Un texte peut mélanger plusieurs types !**\nUn roman = narratif + descriptif + dialogues\n\n🎯 **Question** : Quel type de texte est une recette de cuisine ? Et un article de journal ?` },

  { motsCles: ["genre littéraire","roman","nouvelle","poésie","théâtre","autobiographie","essai","conte","fable"],
    reponse: () => `📚 **Les genres littéraires**\n\n📚 **ROMAN** — texte narratif long, personnages fictifs\n→ Sous-genres : policier, SF, historique, sentimental\n\n📚 **NOUVELLE** — récit court, peu de personnages, chute souvent inattendue\n\n📚 **POÉSIE** — jeu sur le rythme, les sons, les images\n→ Vers, strophes, rimes ; peut ne pas raconter d'histoire\n\n📚 **THÉÂTRE** — dialogues, didascalies, destiné à être joué\n→ Actes et scènes ; tragédie vs comédie\n\n📚 **AUTOBIOGRAPHIE** — l'auteur raconte SA propre vie\n→ Pacte autobiographique : auteur = narrateur = personnage principal\n\n📚 **CONTE** — histoire merveilleuse avec une morale\n→ Formules : "Il était une fois..." / "...ils vécurent heureux"\n\n📚 **FABLE** — court récit avec morale explicite (souvent animaux)\n→ Ex : La Fontaine (*Le Corbeau et le Renard*)\n\n💡 **Repères chronologiques**\nMoyen Âge → Renaissance → Classicisme (XVII) → Romantisme (XIX) → Réalisme → XXème\n\n🎯 **Question** : Dans *Les Misérables* de Victor Hugo, quel est le genre principal et quel mouvement littéraire représente-t-il ?` },

  { motsCles: ["versification","rime","vers","strophe","alexandrin","syllabe","sonnet","quatrain","tercet"],
    reponse: () => `📚 **La versification (poésie)**\n\n📖 **Compter les syllabes**\nOn compte toutes les syllabes, mais le *e* muet en fin de mot ne compte pas devant une voyelle.\n*"Le chat dor(e) au soleil"* = 6 syllabes\n\n📖 **Les types de vers**\n• **Alexandrin** = 12 syllabes (le plus noble)\n• **Décasyllabe** = 10 syllabes\n• **Octosyllabe** = 8 syllabes\n\n📖 **Les strophes**\n• **Quatrain** = 4 vers · **Tercet** = 3 vers · **Distique** = 2 vers\n• **Sonnet** = 2 quatrains + 2 tercets (forme classique)\n\n📖 **Les rimes**\n• **Plates/suivies** : AABB → *lune/brune, ciel/miel*\n• **Croisées** : ABAB\n• **Embrassées** : ABBA\n\n📖 **Le rythme**\n• **Césure** : coupure au milieu d'un alexandrin (après la 6ème syllabe)\n• **Enjambement** : phrase qui déborde sur le vers suivant\n• **Rejet** : début d'une phrase placé à la fin du vers précédent\n\n🎯 **Question** : Compte les syllabes de *"Demain, dès l'aube, à l'heure où blanchit la campagne"* (Victor Hugo).` },

  { motsCles: ["accord participe passé","participe passé","auxiliaire avoir","auxiliaire être","accord participe"],
    reponse: () => `📚 **L'accord du participe passé**\n\n📖 **Règle 1 — avec ÊTRE**\nLe participe s'accorde avec le **sujet**.\n*Elle est partie.* → partie (féminin singulier)\n*Ils sont arrivés.* → arrivés (masculin pluriel)\n\n📖 **Règle 2 — avec AVOIR**\nLe participe s'accorde avec le **COD placé AVANT** le verbe.\nSans COD avant → **pas d'accord** :\n*J'ai mangé des pommes.* → mangé (COD après = pas d'accord)\n*Les pommes que j'ai mangées.* → mangées (COD "les pommes" est avant)\n\n📖 **Règle 3 — verbes pronominaux**\n*Ils se sont lavés.* (se = COD → accord)\n*Elles se sont parlé.* (se = COI → pas d'accord)\n\n💡 **Astuce : tester le COD**\nSi on peut répondre à "Quoi ?" ou "Qui ?" avant le verbe → accord\n\n🎯 **Question** : Accorde si nécessaire : *Elle a (pris) les photos que j'avais (fait).*` },

  /* ════════════════════════════════════════
     🌍 HISTOIRE-GÉOGRAPHIE
     ════════════════════════════════════════ */

  { motsCles: ["première guerre mondiale","grande guerre","1914","1918","verdun","armistice","tranchees"],
    reponse: () => `📚 **La Première Guerre mondiale (1914-1918)**\n\n🔑 **Dates clés**\n• **28 juin 1914** : assassinat de l'archiduc François-Ferdinand à Sarajevo → déclenchement\n• **Août 1914** : entrée en guerre des grandes puissances européennes\n• **1916** : bataille de Verdun (300 000 morts) et de la Somme\n• **1917** : entrée des États-Unis ; révolution bolchévique en Russie\n• **11 novembre 1918** : armistice\n\n📖 **Causes**\n• Rivalités entre puissances européennes\n• Système d'alliances (Triple Entente vs Triple Alliance)\n• Nationalisme et colonialisme\n• Course aux armements\n\n📖 **La guerre des tranchées**\nConditions horribles (boue, rats, gaz), millions de morts pour quelques km conquis.\n\n💡 **Bilan**\n18 millions de morts · Traité de Versailles (1919) · L'Allemagne déclarée responsable\nRedécoupage de la carte de l'Europe · Création de la SDN\n\n🎯 **Question** : Pourquoi dit-on que la 1ère Guerre mondiale est une "guerre totale" ?` },

  { motsCles: ["seconde guerre mondiale","deuxième guerre mondiale","1939","1945","hitler","nazisme","résistance","débarquement","shoah","vichy","occupation"],
    reponse: () => `📚 **La Seconde Guerre mondiale (1939-1945)**\n\n🔑 **Dates clés**\n• **1er septembre 1939** : invasion de la Pologne → début\n• **Juin 1940** : défaite française, appel du 18 juin (De Gaulle)\n• **6 juin 1944** : débarquement en Normandie\n• **8 mai 1945** : capitulation de l'Allemagne (VE Day)\n• **6 et 9 août 1945** : bombes atomiques sur Hiroshima et Nagasaki\n• **2 septembre 1945** : capitulation du Japon — fin de la guerre\n\n📖 **La Shoah**\nExtermination systématique de **6 millions de Juifs** par le régime nazi → génocide, crime contre l'humanité · Camps d'extermination : Auschwitz, Treblinka...\n\n📖 **La France sous l'Occupation**\n• Zone occupée (nord) + Zone libre (sud, régime de Vichy = collaboration)\n• Résistance : intérieure (maquis, réseaux) et extérieure (France Libre, CNR)\n\n💡 **Bilan**\n60 millions de morts · Création de l'ONU (1945) · Procès de Nuremberg · Début de la Guerre froide\n\n🎯 **Question** : Qu'est-ce que la collaboration ? En quoi diffère-t-elle de la résistance ?` },

  { motsCles: ["colonisation","empire colonial","colonies","colonialisme","impérialisme"],
    reponse: () => `📚 **La colonisation (XIX - début XX siècle)**\n\n🔑 **Définition**\nLa colonisation = domination d'un pays (métropole) sur des territoires étrangers (colonies) en Afrique, Asie, Océanie.\n\n📖 **Motivations des colonisateurs**\n• **Économiques** : ressources naturelles (or, caoutchouc, coton), marchés\n• **Politiques** : prestige, puissance militaire\n• **Idéologiques** : "mission civilisatrice" (idée raciste de supériorité européenne)\n\n📖 **Les méthodes**\n• Conquête militaire\n• Mise en place d'une administration européenne\n• Exploitation du travail des populations locales\n\n📖 **Les grandes puissances coloniales**\nRoyaume-Uni, France, Belgique, Allemagne, Portugal, Espagne\n→ France : Afrique subsaharienne, Maghreb, Indochine\n\n💡 **À retenir**\n• Conférence de Berlin (1885) : partage de l'Afrique entre puissances européennes\n• Les populations colonisées perdent leur liberté, leur culture est souvent niée\n\n🎯 **Question** : Quelles sont les différentes motivations qui poussent les Européens à coloniser ?` },

  { motsCles: ["décolonisation","indépendance","guerre d'algérie","afrique indépendance","inde indépendance"],
    reponse: () => `📚 **La décolonisation (1945-1975)**\n\n🔑 **Définition**\nProcessus par lequel les colonies obtiennent leur indépendance après la Seconde Guerre mondiale.\n\n📖 **Causes**\n• La WWII a affaibli les puissances coloniales\n• Les idéaux de liberté et de démocratie (ONU, 1945)\n• Mouvements nationalistes dans les colonies\n• Soutien de l'URSS et des USA aux indépendances\n\n📖 **Deux types de décolonisation**\n**Pacifique** : Inde (1947, Gandhi), Afrique subsaharienne française (1960)\n**Violente** : Algérie (1954-1962, guerre d'indépendance), Indochine (1946-1954)\n\n📖 **La guerre d'Algérie (1954-1962)**\nAlgérie = colonie de peuplement française → guerre très violente → accords d'Évian (1962) → indépendance\n\n💡 **Bilan**\n• Création de nouveaux États (souvent avec des frontières héritées de la colonisation)\n• Dépendance économique persistante (néo-colonialisme)\n\n🎯 **Question** : Pourquoi certaines décolonisations ont-elles été pacifiques et d'autres violentes ?` },

  { motsCles: ["guerre froide","urss","bloc de l'est","bloc de l'ouest","rideau de fer","mur de berlin","cuba","otan"],
    reponse: () => `📚 **La Guerre froide (1947-1991)**\n\n🔑 **Définition**\nAffrontement indirect (sans combat direct) entre les **USA** (capitalisme, démocratie) et l'**URSS** (communisme, régime soviétique) après 1945.\n\n📖 **Les deux blocs**\n• **Bloc occidental** : USA + Europe de l'Ouest (OTAN 1949)\n• **Bloc oriental** : URSS + Europe de l'Est (Pacte de Varsovie 1955)\n\n📖 **Étapes clés**\n• **1947** : doctrine Truman, plan Marshall → début de la Guerre froide\n• **1949** : bombe atomique soviétique → course aux armements\n• **1961** : construction du Mur de Berlin\n• **1962** : crise des missiles de Cuba → risque de guerre nucléaire !\n• **1989** : chute du Mur de Berlin\n• **1991** : dissolution de l'URSS → fin de la Guerre froide\n\n💡 **À retenir**\n• Course aux armements (bombes nucléaires), course à l'espace\n• Conflits "par procuration" (Corée, Vietnam)\n\n🎯 **Question** : Pourquoi dit-on que la Guerre froide est une "guerre" alors qu'il n'y a pas de combats directs ?` },

  { motsCles: ["mondialisation","échanges mondiaux","flux mondiaux","firme multinationale","libre-échange","fmn"],
    reponse: () => `📚 **La mondialisation**\n\n🔑 **Définition**\nLa mondialisation = intensification des échanges (marchandises, capitaux, personnes, informations) à l'échelle mondiale.\n\n📖 **Les flux mondiaux**\n• **Flux de marchandises** : conteneurs, ports (Rotterdam, Singapour, Shanghai)\n• **Flux financiers** : bourses, banques, FMI\n• **Flux humains** : migrations, tourisme\n• **Flux d'informations** : internet, médias\n\n📖 **Les acteurs**\n• **FMN** (Firmes MultiNationales) : ex Nike, Apple, Toyota → produisent partout dans le monde\n• **États** : négocient des accords commerciaux (OMC)\n• **ONG** : critiquent les inégalités de la mondialisation\n\n📖 **Les inégalités**\n• Nord (pays riches, triade : USA/Europe/Japon) vs Sud (pays en développement)\n• Chine et Brésil = pays émergents\n\n💡 **À retenir**\n• La mondialisation crée des richesses mais aggrave les inégalités\n• Elle favorise les délocalisations\n\n🎯 **Question** : Qu'est-ce qu'une firme multinationale ? Donne un exemple et explique comment elle profite de la mondialisation.` },

  { motsCles: ["développement durable","environnement","écologie","réchauffement climatique","énergie renouvelable","biodiversité","accord de paris"],
    reponse: () => `📚 **Le développement durable**\n\n🔑 **Définition (Brundtland, 1987)**\n"Répondre aux besoins du présent sans compromettre la capacité des générations futures à répondre aux leurs."\n\n📖 **Les 3 piliers**\n• **Économique** : croissance et création de richesses\n• **Social** : équité, réduction des inégalités\n• **Environnemental** : préservation des ressources naturelles\n\n📖 **Les grands problèmes environnementaux**\n• Réchauffement climatique (CO₂, effet de serre)\n• Déforestation, pollution des océans\n• Disparition de la biodiversité\n• Épuisement des ressources fossiles\n\n📖 **Les solutions**\n• Énergies renouvelables (solaire, éolien, hydraulique)\n• Agriculture biologique, circuits courts\n• Accords de Paris (2015) sur le climat\n\n💡 **À retenir**\n• L'ODD (Objectifs de Développement Durable) de l'ONU : 17 objectifs pour 2030\n\n🎯 **Question** : Explique le concept de "développement durable" en te servant des 3 piliers.` },

  /* ════════════════════════════════════════
     🔬 SVT
     ════════════════════════════════════════ */

  { motsCles: ["adn","gène","génétique","chromosome","hérédité","allèle","mutation","phénotype","génotype"],
    reponse: () => `📚 **L'ADN et la génétique**\n\n🔑 **Définitions clés**\n• **ADN** = molécule en double hélice qui porte l'information génétique\n• **Gène** = portion d'ADN qui code une caractéristique (ex : couleur des yeux)\n• **Allèle** = version d'un gène (ex : allèle "yeux bleus" / "yeux marron")\n• **Chromosome** = structure portant l'ADN (46 chez l'humain = 23 paires)\n• **Phénotype** = ce qu'on observe (ex : yeux marron)\n• **Génotype** = les allèles possédés (ex : Mm)\n\n📖 **Organisation de l'information génétique**\nCellule → **Noyau** → Chromosomes → **Gènes** → ADN\n\n📖 **Chromosomes sexuels**\n• Femme : **XX** · Homme : **XY**\n\n📖 **Dominant/Récessif**\n• Allèle **dominant** (A) : s'exprime même avec un seul exemplaire\n• Allèle **récessif** (a) : s'exprime seulement si en double exemplaire (aa)\n\n💡 **À retenir**\n• ADN présent dans TOUTES les cellules sauf globules rouges\n• Mutation = modification de l'ADN (naturelle ou provoquée)\n\n🎯 **Question** : Deux parents aux yeux marron (Mm) peuvent-ils avoir un enfant aux yeux bleus (mm) ? Justifie avec un échiquier.` },

  { motsCles: ["photosynthèse","chlorophylle","chloroplaste","glucose","co2","lumière solaire","plante verte"],
    reponse: () => `📚 **La photosynthèse**\n\n🔑 **Définition**\nProcessus par lequel les **plantes** et algues fabriquent leur matière organique (glucose) à partir de matière minérale, grâce à l'énergie lumineuse.\n\n📖 **L'équation bilan**\n**CO₂ + H₂O + lumière → glucose (C₆H₁₂O₆) + O₂**\n(dioxyde de carbone + eau → sucre + oxygène)\n\n📖 **Où ça se passe**\n• Dans les **feuilles** → dans les **chloroplastes** des cellules\n• Les chloroplastes contiennent la **chlorophylle** (pigment vert) qui capte la lumière\n\n📖 **Conditions nécessaires**\nLumière + eau (racines) + CO₂ (stomates/pores des feuilles)\n\n💡 **Conséquences essentielles**\n• Produit l'O₂ que tous les êtres vivants respirent\n• Stocke l'énergie solaire sous forme de glucose\n• Base de TOUTES les chaînes alimentaires\n• La nuit : les plantes ne photosynthétisent plus, elles respirent comme nous\n\n🎯 **Question** : Pourquoi les plantes ont-elles besoin de lumière pour survivre ? Et pourquoi sont-elles vertes ?` },

  { motsCles: ["respiration cellulaire","mitochondrie","atp","energie cellulaire","dioxyde de carbone cellule"],
    reponse: () => `📚 **La respiration cellulaire**\n\n🔑 **Définition**\nLa respiration cellulaire = processus par lequel les cellules dégradent le glucose pour produire de l'énergie (ATP).\n\n📖 **L'équation bilan**\n**Glucose + O₂ → CO₂ + H₂O + énergie (ATP)**\n(C'est l'inverse de la photosynthèse !)\n\n📖 **Où ça se passe**\nDans les **mitochondries** de TOUTES les cellules des êtres vivants (animaux, plantes, champignons)\n\n📖 **Différence photosynthèse vs respiration**\n| | Photosynthèse | Respiration |\n|---|---|---|\n| Qui ? | Plantes uniquement | Tous les êtres vivants |\n| Quand ? | Le jour seulement | En permanence |\n| Consomme | CO₂ + H₂O | O₂ + glucose |\n| Produit | O₂ + glucose | CO₂ + H₂O + énergie |\n\n💡 **À retenir**\n• ATP = "monnaie énergétique" de la cellule\n• L'effort physique augmente la respiration cellulaire\n\n🎯 **Question** : Pourquoi respire-t-on plus vite quand on fait du sport ? Fais le lien avec la respiration cellulaire.` },

  { motsCles: ["système immunitaire","immunité","anticorps","lymphocyte","vaccination","antigène","infection"],
    reponse: () => `📚 **Le système immunitaire**\n\n🔑 **Définition**\nEnsemble des défenses de l'organisme contre les agents pathogènes (bactéries, virus, parasites).\n\n📖 **Les 2 types de défenses**\n**Immunité innée (non spécifique) — 1ère ligne**\n• Peau, muqueuses (barrières physiques)\n• Phagocytes (globules blancs qui "mangent" les envahisseurs)\n• Inflammation, fièvre\n\n**Immunité adaptative (spécifique) — 2ème ligne**\n• **Lymphocytes B** → produisent des **anticorps** (protéines qui neutralisent l'antigène)\n• **Lymphocytes T** → détruisent directement les cellules infectées\n• **Mémoire immunitaire** : après une première infection, la réponse est plus rapide\n\n📖 **La vaccination**\nInjecter un antigène affaibli ou inactivé → le corps fabrique des anticorps → **mémoire** → protection lors d'une vraie infection\n\n💡 **Vocabulaire**\n• **Antigène** = substance étrangère reconnue comme dangereuse\n• **Anticorps** = protéine produite par les lymphocytes B pour neutraliser l'antigène\n\n🎯 **Question** : Explique comment un vaccin protège contre une maladie.` },

  { motsCles: ["système nerveux","neurone","cerveau","réflexe","influx nerveux","moelle épinière"],
    reponse: () => `📚 **Le système nerveux**\n\n🔑 **Organisation**\n• **SNC** (Système Nerveux Central) : cerveau + moelle épinière\n• **SNP** (Système Nerveux Périphérique) : nerfs qui relient le SNC au corps\n\n📖 **Le neurone**\nCellule nerveuse qui transmet l'**influx nerveux** (signal électrique) :\nDendrites → Corps cellulaire → Axone → Synapse\n\n📖 **Les voies nerveuses**\n**Voie sensorielle** (afférente) : récepteur → SNC (on perçoit)\n**Voie motrice** (efférente) : SNC → muscle (on agit)\n\n📖 **L'arc réflexe**\nRéponse automatique et rapide SANS passer par le cerveau :\nStimulus → Récepteur → Moelle épinière → Effecteur (muscle)\nEx : retirer la main d'une flamme, rotule au marteau\n\n📖 **Zones du cerveau**\n• Cortex moteur : contrôle les mouvements volontaires\n• Cortex sensoriel : traite les sensations\n• Zones du langage : aire de Broca (parole), Wernicke (compréhension)\n\n🎯 **Question** : Explique la différence entre un acte réflexe et un acte volontaire.` },

  { motsCles: ["évolution","darwin","selection naturelle","espèce","ancêtre commun","fossile","adaptation"],
    reponse: () => `📚 **L'évolution des espèces (Darwin)**\n\n🔑 **La théorie de Darwin (1859)**\nLes espèces évoluent au fil du temps par **sélection naturelle**.\n\n📖 **Mécanisme de la sélection naturelle**\n1. **Variabilité** : les individus d'une espèce sont différents les uns des autres\n2. **Hérédité** : ces différences se transmettent aux descendants\n3. **Sélection** : les individus les mieux adaptés à leur environnement survivent et se reproduisent plus\n4. **Évolution** : les caractères favorables se répandent dans la population\n\n📖 **Preuves de l'évolution**\n• **Fossiles** : traces d'êtres vivants disparus montrant des formes intermédiaires\n• **Anatomie comparée** : membres des vertébrés (bras/aile/nageoire = même structure de base)\n• **ADN** : plus deux espèces sont proches, plus leur ADN est similaire\n\n📖 **Ancêtre commun**\nToutes les espèces actuelles descendent d'ancêtres communs.\nEx : l'Homme et le chimpanzé ont un ancêtre commun (99% d'ADN identique)\n\n💡 **À retenir**\n• L'évolution est lente (millions d'années)\n• L'environnement "sélectionne" les caractères\n\n🎯 **Question** : Explique comment la girafe a pu avoir un long cou selon Darwin.` },

  { motsCles: ["ecosystème","chaîne alimentaire","biodiversité","prédateur","proie","producteur","consommateur","décomposeur"],
    reponse: () => `📚 **Écosystèmes et chaînes alimentaires**\n\n🔑 **Définitions**\n• **Écosystème** = milieu naturel + tous les êtres vivants qui y vivent\n• **Biocénose** = ensemble des êtres vivants d'un écosystème\n• **Biotope** = milieu physique (sol, eau, climat)\n\n📖 **Chaîne alimentaire**\n**Producteur → Consommateur 1er ordre → Consommateur 2ème ordre → Décomposeur**\nEx : Herbe → Lapin → Renard → Bactéries\n\n📖 **Les rôles dans la chaîne**\n• **Producteurs** (végétaux) : fabriquent la matière organique par photosynthèse\n• **Consommateurs** (animaux) : mangent d'autres êtres vivants\n• **Décomposeurs** (bactéries, champignons) : dégradent la matière organique morte\n\n💡 **À retenir**\n• L'énergie se perd à chaque maillon (10% seulement transmise)\n• Disparition d'une espèce → déséquilibre de tout l'écosystème\n• Biodiversité = richesse en espèces → plus elle est grande, plus l'écosystème est stable\n\n🎯 **Question** : Que se passerait-il dans l'écosystème si les renards disparaissaient ?` },

  /* ════════════════════════════════════════
     ⚗️ PHYSIQUE-CHIMIE
     ════════════════════════════════════════ */

  { motsCles: ["vitesse","v=d/t","distance temps","rapidité","km/h","m/s"],
    reponse: () => `📚 **La vitesse — v = d / t**\n\n🔑 **La formule et ses dérivées**\n• **v = d / t** (vitesse = distance ÷ durée)\n• **d = v × t** (distance = vitesse × durée)\n• **t = d / v** (durée = distance ÷ vitesse)\n\n📖 **Unités**\nv : m/s ou km/h · d : m ou km · t : s ou h\n\n✏️ **Exemples**\n• 120 km en 2 h → v = 120/2 = **60 km/h**\n• v = 20 m/s pendant 5 s → d = 20×5 = **100 m**\n\n📖 **Conversions indispensables**\n• km/h → m/s : **÷ 3,6**\n• m/s → km/h : **× 3,6**\nEx : 90 km/h = 90/3,6 = **25 m/s**\n\n📖 **Types de mouvement**\n• **Rectiligne uniforme** : v constante, trajectoire droite\n• **Rectiligne uniformément accéléré** : vitesse augmente régulièrement\n• **Circulaire** : trajectoire en cercle\n\n🎯 **Question** : Un cycliste parcourt 45 km en 1h30. Quelle est sa vitesse en km/h et en m/s ?` },

  { motsCles: ["electricite","tension","intensité","résistance","loi d'ohm","volt","ampere","circuit","serie","derivation"],
    reponse: () => `📚 **Électricité — Loi d'Ohm**\n\n🔑 **Les 3 grandeurs électriques**\n• **Tension U** (Volts, V) → mesurée avec un **voltmètre en dérivation**\n• **Intensité I** (Ampères, A) → mesurée avec un **ampèremètre en série**\n• **Résistance R** (Ohms, Ω) → caractérise un dipôle\n\n📖 **Loi d'Ohm**\n**U = R × I** → aussi : R = U/I et I = U/R\n\n✏️ **Exemple** : R = 100 Ω, I = 0,2 A → U = 20 V\n\n📖 **Lois pour les circuits**\n**Circuit en SÉRIE :**\n• Intensité la même partout : I₁ = I₂ = I\n• Tensions s'additionnent : U = U₁ + U₂\n\n**Circuit en DÉRIVATION :**\n• Tension la même sur chaque branche : U₁ = U₂ = U\n• Intensités s'additionnent : I = I₁ + I₂\n\n💡 **Puissance électrique**\n**P = U × I** (en Watts, W)\nÉnergie : **E = P × t** (en Joules J ou Wh)\n\n🎯 **Question** : Dans un circuit série, U = 12 V, R₁ = 30 Ω, R₂ = 10 Ω. Calcule l'intensité et la tension aux bornes de chaque résistance.` },

  { motsCles: ["force","poids","masse","newton","gravité","réaction","action réciproque"],
    reponse: () => `📚 **Les forces**\n\n🔑 **Définition**\nUne force est une action mécanique exercée par un objet sur un autre.\nElle se représente par un **vecteur** (flèche) : point d'application, direction, sens, valeur.\n\n📖 **Force = vecteur** (notation : F avec une flèche)\n• **Intensité** (valeur) en Newtons (N)\n• **Direction** (horizontale, verticale...)\n• **Sens** (vers le haut, vers le bas...)\n\n📖 **Le poids et la masse**\n• **Masse m** (kg) : quantité de matière → **invariable** (même sur la Lune !)\n• **Poids P** (N) : force exercée par la gravité → **varie selon la planète**\n• Relation : **P = m × g** (g = 9,8 N/kg sur Terre ≈ 10)\nEx : m = 5 kg → P = 5 × 10 = **50 N**\n\n📖 **Équilibre**\nUn objet est en équilibre si la somme des forces = 0\n→ Réaction du support = poids (opposé, vertical)\n\n💡 **Loi de Newton (3ème loi)**\nSi A exerce une force sur B, alors B exerce une force égale et opposée sur A.\n\n🎯 **Question** : Un livre de masse 0,3 kg est posé sur une table. Quel est son poids ? Quelles forces s'exercent sur lui ?` },

  { motsCles: ["énergie","formes d'énergie","rendement","energie cinétique","énergie potentielle","conservation énergie","joule","watt"],
    reponse: () => `📚 **L'énergie**\n\n🔑 **Définition**\nL'énergie est la capacité à produire un travail ou un changement.\nUnité : **Joule (J)** · Puissance : **Watt (W = J/s)**\n\n📖 **Formes d'énergie**\n• **Cinétique** : énergie du mouvement → Ec = ½ × m × v²\n• **Potentielle de pesanteur** : énergie de position → Ep = m × g × h\n• **Thermique** (chaleur), **chimique** (aliments, carburant), **électrique**, **lumineuse**, **nucléaire**\n\n📖 **Conservation de l'énergie**\nL'énergie ne se crée pas ni ne se détruit, elle se **convertit** d'une forme à une autre.\nEx : panneau solaire : énergie lumineuse → électrique\n\n📖 **Rendement**\n**r = énergie utile / énergie totale** (en % ou entre 0 et 1)\nEx : ampoule → 95% chaleur + 5% lumière → rendement lumineux = 5%\n\n💡 **Énergie électrique**\n• E = P × t (P en W, t en secondes → E en Joules)\n\n🎯 **Question** : Une voiture de 1000 kg roule à 20 m/s. Calcule son énergie cinétique.` },

  { motsCles: ["atome","molécule","ion","élément chimique","tableau périodique","proton","neutron","électron","noyau atomique"],
    reponse: () => `📚 **Atomes et molécules**\n\n🔑 **L'atome**\n• **Noyau** : protons (+) + neutrons (neutres) → très petit, très dense\n• **Électrons** (−) : orbitent autour du noyau\n• Atome = électriquement **neutre** (nb protons = nb électrons)\n\n📖 **Numéro atomique Z**\n= nombre de protons (identifie l'élément)\nEx : H → Z=1, He → Z=2, C → Z=6, O → Z=8, Na → Z=11\n\n📖 **Ions**\nAtome qui a gagné ou perdu des électrons :\n• Cation (+) : a perdu des e⁻ → Na⁺, Ca²⁺\n• Anion (−) : a gagné des e⁻ → Cl⁻, O²⁻\n\n📖 **Molécules**\nAssociation d'atomes liés par des liaisons chimiques :\n• H₂O (eau) = 2 atomes H + 1 atome O\n• CO₂ = 1 C + 2 O\n• CH₄ (méthane) = 1 C + 4 H\n\n💡 **Formule chimique**\nH₂SO₄ : 2 H, 1 S, 4 O\nLa formule indique le nombre de chaque type d'atome\n\n🎯 **Question** : Combien d'atomes de chaque élément y a-t-il dans : C₆H₁₂O₆ (glucose) ?` },

  { motsCles: ["réaction chimique","équation bilan","réactif","produit","conservation masse","combustion","lavoisier"],
    reponse: () => `📚 **Les réactions chimiques**\n\n🔑 **Définition**\nUne réaction chimique transforme des **réactifs** en **produits**.\nLes liaisons entre atomes sont brisées et de nouvelles sont formées.\n\n📖 **L'équation chimique**\n**Réactifs → Produits** (flèche ou →)\nEx : 2 H₂ + O₂ → 2 H₂O (combustion de l'hydrogène)\n\n📖 **Loi de conservation de la masse (Lavoisier)**\n"Rien ne se perd, rien ne se crée, tout se transforme."\n→ La **masse totale** des réactifs = masse totale des produits\n→ Il y a le **même nombre de chaque atome** avant et après\n\n📖 **Équilibrer une équation**\nAjouter des coefficients pour avoir le même nombre de chaque atome :\nCH₄ + **2**O₂ → CO₂ + **2**H₂O ✅\n\n📖 **Types de réactions courantes**\n• **Combustion** : réaction avec O₂ → CO₂ + H₂O + énergie\n• **Oxydation** : réaction avec O₂ (rouille = oxydation du fer)\n• **Précipitation** : formation d'un solide dans une solution\n\n💡 **À retenir**\n• Ne jamais modifier les indices dans les formules chimiques pour équilibrer !\n• Seulement les coefficients devant les formules\n\n🎯 **Question** : Équilibre l'équation : Al + O₂ → Al₂O₃` },

  { motsCles: ["optique","lumière","rayon lumineux","réfraction","réflexion","lentille","prisme"],
    reponse: () => `📚 **L'optique — La lumière**\n\n🔑 **Propagation de la lumière**\n• La lumière se propage en **ligne droite** dans un milieu homogène\n• Vitesse de la lumière : **c = 3 × 10⁸ m/s** (300 000 km/s)\n• Sources primaires (émettent la lumière) vs sources secondaires (réfléchissent)\n\n📖 **Réflexion**\nQuand la lumière rebondit sur une surface :\n**Angle d'incidence = angle de réflexion** (loi de Descartes)\nEx : miroir plan\n\n📖 **Réfraction**\nChangement de direction quand la lumière change de milieu :\nAir → eau (ou verre) → le rayon se rapproche de la normale\nLoi de Snell-Descartes : n₁ × sin(i₁) = n₂ × sin(i₂)\n\n📖 **Les lentilles**\n• **Lentille convergente** (convexe) : fait converger les rayons → loupe, œil, objectif photo\n• **Lentille divergente** (concave) : fait diverger les rayons → verres de myopes\n\n📖 **Décomposition de la lumière**\nLa lumière blanche = mélange de toutes les couleurs → prisme → arc-en-ciel\n\n🎯 **Question** : Pourquoi voit-on une paille "cassée" dans un verre d'eau ? Quel phénomène explique cela ?` }

];

/* ═══════════════════════════════════════════════════════════════════════════
   NETTOYAGE DE LA REQUÊTE
   Supprime les préfixes de question courants en français pour faciliter
   la correspondance avec les mots-clés des leçons.
   ═══════════════════════════════════════════════════════════════════════════ */
function cleanQuery(message) {
  return message
    .replace(/^(dis[- ]moi |explique[- ]moi |j'?aimerais savoir |peux[- ]tu (?:m'?expliquer|me dire) |parle[- ]moi (?:de |d')|donne[- ]moi (?:des )?(?:infos?|informations?|détails?) (?:sur |à propos de )?|je (?:veux|voudrais) savoir |c'est quoi |qu'est[- ]ce qu'?|qu'est[- ]ce |qu'?est |qui (?:est|était|sont) |comment (?:fonctionne |marche |faire |s'appelle )?|pourquoi |où (?:est|se trouve|sont) |quand (?:a été|fut|est) |quel(?:le)?s? (?:est|était|sont) (?:le |la |les |l')?|recherche(?:r)? |cherche(?:r)? |explique(?:r)? )/gi, "")
    .replace(/[?!.]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/* ═══════════════════════════════════════════════════════════════════════════
   RECHERCHE DANS LES LEÇONS
   Retourne la réponse de la première leçon dont un mot-clé correspond,
   ou null si aucune correspondance.
   ═══════════════════════════════════════════════════════════════════════════ */
function findLesson(message) {
  const norm = s => s.toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
  const q = norm(message);
  for (const lesson of LESSONS) {
    if (lesson.motsCles.some(kw => q.includes(norm(kw)))) {
      return lesson.reponse(q);
    }
  }
  return null;
}
